$schema: "http://json-schema.org/draft-07/schema#"

title: mOTUs config file

properties:
  samples:
    type: string
  mcr:
    type: object
    properties:
      mcr:
        type: object
        properties:
          download:
            type: string
          mcr_path:
            type: string
        required:
          - mcr_path
      threshold:
        type: number
        mininum: 0.0
        maximum: 1.0
        default: 0.7
      blocksize:
        type: integer
        minimum: 1
        maximum: 100000
        default: 1000
required:
  - samples